import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { Card } from "@/components/ui/card";
import { Callout } from "@/components/ui/callout";
import { buttonClassName } from "@/components/ui/button";
import { CheckIcon, ShieldCheckIcon } from "@/components/ui/icons";

export const metadata: Metadata = {
  title: "Request submitted · Request a refund",
  description: "Your refund request has been received.",
  // A confirmation page keyed to one person's reference has no business in
  // search results.
  robots: { index: false, follow: false },
};

/**
 * The reference is produced by the integration, so the application cannot
 * assume a format. This checks only that the value is safe to render and
 * plausibly a reference — it is read straight from the URL, so it must never be
 * echoed back unchecked.
 */
const REFERENCE_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$/;

/**
 * Confirmation screen.
 *
 * `searchParams` is a Promise in Next.js 16 — synchronous access was removed in
 * this major. `PageProps<'/refund/success'>` is generated by `next typegen` and
 * types the route's params for us.
 */
export default async function SuccessPage(props: PageProps<"/refund/success">) {
  const { reference } = await props.searchParams;
  const value = Array.isArray(reference) ? reference[0] : reference;

  // The reference is displayed, so it is validated before being rendered rather
  // than echoed back. Anything else means a hand-edited URL.
  if (!value || !REFERENCE_PATTERN.test(value)) {
    redirect("/refund/details");
  }

  return (
    <div className="mx-auto max-w-2xl">
      <Card className="p-6 sm:p-8">
        <div className="flex size-12 items-center justify-center rounded-full bg-success-subtle text-success">
          <CheckIcon className="size-6" />
        </div>

        <h1 className="mt-5 text-2xl font-semibold text-foreground">Request submitted</h1>
        <p className="mt-2 text-sm text-muted">
          Thanks — we have everything we need. Keep this reference in case you need to contact us
          about your refund.
        </p>

        <div className="mt-6 rounded-xl border border-border-subtle bg-surface-muted px-5 py-4">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted">
            Your reference
          </p>
          <p className="mt-1 font-mono text-xl font-semibold tracking-wide text-foreground">
            {value}
          </p>
        </div>

        <Callout tone="info" title="Secure processing" icon={<ShieldCheckIcon />} className="mt-6">
          Your information is encrypted and will be reviewed within 2–3 business days.
        </Callout>

        <div className="mt-7 border-t border-border-subtle pt-5">
          <Link href="/refund/details" className={buttonClassName("secondary")}>
            Start another request
          </Link>
        </div>
      </Card>
    </div>
  );
}
